//
//  RawProvinceDict.swift
//  Onderoad
//
//  Created by Giuseppe Trentadue on 29/06/17.
//  Copyright © 2017 Giuseppe Trentadue. All rights reserved.
//

import Foundation

public class RawProvinceDict{

	let DICT = [
		"Provincia di Agrigento" : "Agrigento",
		"Provincia di Alessandria" : "Alessandria",
		"Provincia di Ancona" : "Ancona",
		"Provincia di Arezzo" : "Arezzo",
		"Provincia di Ascoli Piceno" : "Ascoli Piceno",
		"Provincia di Asti" : "Asti",
		"Provincia di Avellino" : "Avellino",
		"Città Metropolitana di Bari" : "Bari",
		"Provincia di Barletta-Andria-Trani" : "Barletta-Andria-Trani",
		"Provincia di Belluno" : "Belluno",
		"Provincia di Benevento" : "Benevento",
		"Provincia di Bergamo" : "Bergamo",
		"Provincia di Biella" : "Biella",
		"Città Metropolitana di Bologna" : "Bologna",
		"Provincia di Bolzano" : "Bolzano",
		"Provincia di Brescia" : "Brescia",
		"Provincia di Brindisi" : "Brindisi",
		"Provincia di Cagliari" : "Cagliari",
		"Provincia di Caltanissetta" : "Caltanissetta",
		"Provincia di Campobasso" : "Campobasso",
		"Provincia di Carbonia-Iglesias" : "Carbonia-Iglesias",
		"Provincia di Caserta" : "Caserta",
		"Città Metropolitana di Catania" : "Catania",
		"Provincia di Catanzaro" : "Catanzaro",
		"Provincia di Chieti" : "Chieti",
		"Provincia di Como" : "Como",
		"Provincia di Cosenza" : "Cosenza",
		"Provincia di Cremona" : "Cremona",
		"Provincia di Crotone" : "Crotone",
		"Provincia di Cuneo" : "Cuneo",
		"Provincia di Enna" : "Enna",
		"Provincia di Fermo" : "Fermo",
		"Provincia di Ferrara" : "Ferrara",
		"Città Metropolitana di Firenze" : "Firenze",
		"Provincia di Foggia" : "Foggia",
		"Provincia di Forlì-Cesena" : "Forlì-Cesena",
		"Provincia di Frosinone" : "Frosinone",
		"Città Metropolitana di Genova" : "Genova",
		"Provincia di Gorizia" : "Gorizia",
		"Provincia di Grosseto" : "Grosseto",
		"Provincia di Imperia" : "Imperia",
		"Provincia di Isernia" : "Isernia",
		"Provincia di L'Aquila" : "L'Aquila",
		"Provincia di La Spezia" : "La Spezia",
		"Provincia di Latina" : "Latina",
		"Provincia di Lecce" : "Lecce",
		"Provincia di Lecco" : "Lecco",
		"Provincia di Livorno" : "Livorno",
		"Provincia di Lodi" : "Lodi",
		"Provincia di Lucca" : "Lucca",
		"Provincia di Macerata" : "Macerata",
		"Provincia di Mantova" : "Mantova",
		"Provincia di Massa-Carrara" : "Massa-Carrara",
		"Provincia di Matera" : "Matera",
		"Provincia di Medio Campidano" : "Medio Campidano",
		"Città Metropolitana di Messina" : "Messina",
		"Città Metropolitana di Milano" : "Milano",
		"Provincia di Modena" : "Modena",
		"Provincia di Monza e della Brianza" : "Monza e della Brianza",
		"Città Metropolitana di Napoli" : "Napoli",
		"Provincia di Novara" : "Novara",
		"Provincia di Nuoro" : "Nuoro",
		"Provincia di Ogliastra" : "Ogliastra",
		"Provincia di Olbia-Tempio" : "Olbia-Tempio",
		"Provincia di Oristano" : "Oristano",
		"Provincia di Padova" : "Padova",
		"Città Metropolitana di Palermo" : "Palermo",
		"Provincia di Palermo" : "Palermo",
		"Provincia di Parma" : "Parma",
		"Provincia di Pavia" : "Pavia",
		"Provincia di Perugia" : "Perugia",
		"Provincia di Pesaro e Urbino" : "Pesaro e Urbino",
		"Provincia di Pescara" : "Pescara",
		"Provincia di Piacenza" : "Piacenza",
		"Provincia di Pisa" : "Pisa",
		"Provincia di Pistoia" : "Pistoia",
		"Provincia di Pordenone" : "Pordenone",
		"Provincia di Potenza" : "Potenza",
		"Provincia di Prato" : "Prato",
		"Provincia di Ragusa" : "Ragusa",
		"Provincia di Ravenna" : "Ravenna",
		"Città Metropolitana di Reggio Calabria" : "Reggio Calabria",
		"Provincia di Reggio Emilia" : "Reggio Emilia",
		"Provincia di Rieti" : "Rieti",
		"Provincia di Rimini" : "Rimini",
		"Città Metropolitana di Roma" : "Roma",
		"Provincia di Rovigo" : "Rovigo",
		"Provincia di Salerno" : "Salerno",
		"Provincia di Sassari" : "Sassari",
		"Provincia di Savona" : "Savona",
		"Provincia di Siena" : "Siena",
		"Provincia di Siracusa" : "Siracusa",
		"Provincia di Sondrio" : "Sondrio",
		"Provincia di Taranto" : "Taranto",
		"Provincia di Teramo" : "Teramo",
		"Provincia di Terni" : "Terni",
		"Città Metropolitana di Torino" : "Torino",
		"Provincia di Trapani" : "Trapani",
		"Provincia di Trento" : "Trento",
		"Provincia di Treviso" : "Treviso",
		"Provincia di Trieste" : "Trieste",
		"Provincia di Udine" : "Udine",
		"Provincia di Varese" : "Varese",
		"Città Metropolitana di Venezia" : "Venezia",
		"Valle d'Aosta" : "Valle d'Aosta",
		"Provincia del Verbano-Cusio-Ossola" : "Verbano-Cusio-Ossola",
		"Provincia di Vercelli" : "Vercelli",
		"Provincia di Verona" : "Verona",
		"Provincia di Vibo Valentia" : "Vibo Valentia",
		"Provincia di Vicenza" : "Vicenza",
		"Provincia di Viterbo" : "Viterbo"
	]
}
