//
//  RawProvinceDict.swift
//  Onderoad
//
//  Created by Giuseppe Trentadue on 29/06/17.
//  Copyright © 2017 Giuseppe Trentadue. All rights reserved.
//

import Foundation

public class RawProvinceDict{

	public static let DICT = [
		"Agrigento" : "Agrigento",
		"Alessandria" : "Alessandria",
		"Ancona" : "Ancona",
		"Aosta" : "Aosta",
		"Arezzo" : "Arezzo",
		"Ascoli Piceno" : "Ascoli Piceno",
		"Asti" : "Asti",
		"Avellino" : "Avellino",
		"Città Metropolitana di Bari" : "Bari",
		"Provincia di Barletta-Andria-Trani" : "Barletta-Andria-Trani",
		"Belluno" : "Belluno",
		"Benevento" : "Benevento",
		"Bergamo" : "Bergamo",
		"Biella" : "Biella",
		"Città Metropolitana di Bologna" : "Bologna",
		"Bolzano" : "Bolzano",
		"Brescia" : "Brescia",
		"Brindisi" : "Brindisi",
		"Cagliari" : "Cagliari",
		"Caltanissetta" : "Caltanissetta",
		"Campobasso" : "Campobasso",
		"Carbonia-Iglesias" : "Carbonia-Iglesias",
		"Caserta" : "Caserta",
		"Città Metropolitana di Catania" : "Catania",
		"Catanzaro" : "Catanzaro",
		"Chieti" : "Chieti",
		"Como" : "Como",
		"Cosenza" : "Cosenza",
		"Cremona" : "Cremona",
		"Crotone" : "Crotone",
		"Cuneo" : "Cuneo",
		"Enna" : "Enna",
		"Provincia di Fermo" : "Fermo",
		"Ferrara" : "Ferrara",
		"Città Metropolitana di Firenze" : "Firenze",
		"Foggia" : "Foggia",
		"Forlì-Cesena" : "Forlì-Cesena",
		"Frosinone" : "Frosinone",
		"Città Metropolitana di Genova" : "Genova",
		"Gorizia" : "Gorizia",
		"Grosseto" : "Grosseto",
		"Imperia" : "Imperia",
		"Isernia" : "Isernia",
		"L'Aquila" : "L'Aquila",
		"La Spezia" : "La Spezia",
		"Latina" : "Latina",
		"Lecce" : "Lecce",
		"Lecco" : "Lecco",
		"Livorno" : "Livorno",
		"Lodi" : "Lodi",
		"Lucca" : "Lucca",
		"Macerata" : "Macerata",
		"Mantova" : "Mantova",
		"Massa-Carrara" : "Massa-Carrara",
		"Matera" : "Matera",
		"Medio Campidano" : "Medio Campidano",
		"Città Metropolitana di Messina" : "Messina",
		"Città Metropolitana di Milano" : "Milano",
		"Modena" : "Modena",
		"Provincia di Monza e della Brianza" : "Monza e della Brianza",
		"Città Metropolitana di Napoli" : "Napoli",
		"Novara" : "Novara",
		"Nuoro" : "Nuoro",
		"Ogliastra" : "Ogliastra",
		"Olbia-Tempio" : "Olbia-Tempio",
		"Oristano" : "Oristano",
		"Padova" : "Padova",
		"Città Metropolitana di Palermo" : "Palermo",
		"Parma" : "Parma",
		"Pavia" : "Pavia",
		"Perugia" : "Perugia",
		"Pesaro e Urbino" : "Pesaro e Urbino",
		"Pescara" : "Pescara",
		"Piacenza" : "Piacenza",
		"Pisa" : "Pisa",
		"Pistoia" : "Pistoia",
		"Pordenone" : "Pordenone",
		"Potenza" : "Potenza",
		"Prato" : "Prato",
		"Ragusa" : "Ragusa",
		"Ravenna" : "Ravenna",
		"Città Metropolitana di Reggio Calabria" : "Reggio Calabria",
		"Reggio Emilia" : "Reggio Emilia",
		"Rieti" : "Rieti",
		"Rimini" : "Rimini",
		"Città Metropolitana di Roma" : "Roma",
		"Rovigo" : "Rovigo",
		"Salerno" : "Salerno",
		"Sassari" : "Sassari",
		"Savona" : "Savona",
		"Siena" : "Siena",
		"Siracusa" : "Siracusa",
		"Sondrio" : "Sondrio",
		"Taranto" : "Taranto",
		"Teramo" : "Teramo",
		"Terni" : "Terni",
		"Città Metropolitana di Torino" : "Torino",
		"Trapani" : "Trapani",
		"Trento" : "Trento",
		"Treviso" : "Treviso",
		"Provincia di Trieste" : "Trieste",
		"Udine" : "Udine",
		"Varese" : "Varese",
		"Città Metropolitana di Venezia" : "Venezia",
		"Verbano-Cusio-Ossola" : "Verbano-Cusio-Ossola",
		"Vercelli" : "Vercelli",
		"Verona" : "Verona",
		"Vibo Valentia" : "Vibo Valentia",
		"Vicenza" : "Vicenza",
		"Viterbo" : "Viterbo"
	]
}
