//
//  RegionProvinceDict.swift
//  Onderoad
//
//  Created by Giuseppe Trentadue on 29/06/17.
//  Copyright © 2017 Giuseppe Trentadue. All rights reserved.
//

import Foundation

public class RegionSpotDict{

	static let DICT = [
		"Toscana" : [SpotInfo.init(region: "Toscana", province: "Ms", city: "Marina di carrara", name: "Idrovora", position: CLLocationCoordinate2D.init(latitude:44.0359679, longitude: 10.043825599999991),rating: 0, description: "LATO NORD DEL PORTO DI MARINA DI CARRARA. ATTENZIONE DIVIETO DI BALNEAZIONE E ATTIVITA' NAUTICO SPORTIVE", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Ms", city: "Cinquale", name: "Il trabucco", position: CLLocationCoordinate2D.init(latitude:43.9828071, longitude: 10.153797199999985),rating: 0, description: "AFFIANCO AL RISTORANTE TRABUCCO. LO SPOT PRINCIPALE E' ACCANTO AL MOLETTO DI MASSI", table: SpotInfoTable.init(wave: "DX", wind: "S-O (MODERATO)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Lu", city: "Lido di camaiore", name: "Lido di camaiore", position: CLLocationCoordinate2D.init(latitude:43.9050586, longitude: 10.229172500000004),rating: 0, description: "LUNGO LA SPIAGGIA VARI PICCHI SU SECCHE VARIABILI A DESTRA E SINISTRA DEL MOLO", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Lu", city: "Viareggio", name: "Piazzale mazzini", position: CLLocationCoordinate2D.init(latitude:43.8657267, longitude: 10.2513103),rating: 0, description: "LUNGO LA SPIAGGIA VARI PICCHI SU SECCHE VARIABILI A DESTRA E SINISTRA DEL MOLO", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Lu", city: "Viareggio", name: "Foce del fosso dell'abate", position: CLLocationCoordinate2D.init(latitude:43.8657267, longitude: 10.2513103),rating: 0, description: "SUL VIALE AL MARE, PICCHI SPARSI NON REGGE GRANDI MISURA", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Lu", city: "Viareggio", name: "Tito del molo", position: CLLocationCoordinate2D.init(latitude:43.8657267, longitude: 10.2513103),rating: 0, description: "SUL LATO NORD DEL MOLO DEL PORTO. LAVORA MEGLIO CON VENTO E MARE ATTIVO", table: SpotInfoTable.init(wave: "SX", wind: "S-O (ATTIVO)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Lu", city: "Viareggio", name: "Darsena s/o", position: CLLocationCoordinate2D.init(latitude:43.8657267, longitude: 10.2513103),rating: 0, description: "SULLA LUNGA SPIAGGIA A SUD DI VIAREGGIO VARI PICCHI SU SECCHE VARIABILI", table: SpotInfoTable.init(wave: "DX-SX", wind: "- (ASSENTE)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Pi", city: "Tirrenia", name: "Tirrenia", position: CLLocationCoordinate2D.init(latitude:43.6294361, longitude: 10.29086319999999),rating: 0, description: "VARI PICCHI SU SABBIA REGGE POCO CON MARE ATTIVO", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Livorno", name: "Bagni fiume", position: CLLocationCoordinate2D.init(latitude:43.548473, longitude: 10.310567399999968),rating: 0, description: "A SUD DEL PORTO, ACCANTO ALL'ACCADEMIA NAVALE E DIFRONTE ALL'IPODROMO", table: SpotInfoTable.init(wave: "DX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Livorno", name: "Biscottino", position: CLLocationCoordinate2D.init(latitude:43.548473, longitude: 10.310567399999968),rating: 0, description: "A SUD DEI BAGNI FIUME, DAVANTI AI TRE PONTI VICINO ALLA SCUOLA DI WIDSURF, ADATTO A LONGBOARD", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Livorno", name: "Maroccone", position: CLLocationCoordinate2D.init(latitude:43.548473, longitude: 10.310567399999968),rating: 0, description: "A SUD DI LIVORNO IN UNO SPIAZZO CON LE INDICAZIONI PER MARINA DEL BOCCALE A 200MT DAL CAMPING MIRAMARE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Livorno", name: "Il sale", position: CLLocationCoordinate2D.init(latitude:43.548473, longitude: 10.310567399999968),rating: 0, description: "SPIAGGIA DEL SALE A DESTRA DEI BAGNI ROMA ONDA CORTA MA POTENTE TACK OFF DIFFICILE", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Quercianella", name: "Il golfetto", position: CLLocationCoordinate2D.init(latitude:43.4592601, longitude: 10.36780120000003),rating: 0, description: "A SINISTRA NEL GOLFETTO TRA IL SALE E I BAGNI ROMA", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Quercianella", name: "Bagni roma", position: CLLocationCoordinate2D.init(latitude:43.4592601, longitude: 10.36780120000003),rating: 0, description: "DAVANTI AI BAGNI ROMA NON REGGE MARE ATTIVO", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Quercianella", name: "Lido del rogiolo", position: CLLocationCoordinate2D.init(latitude:43.4592601, longitude: 10.36780120000003),rating: 0, description: "NELL'INSENATURA A SINISTRA DEI BAGNI LIDO DEL ROGIOLO", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Quercianella", name: "Bagni paolieri", position: CLLocationCoordinate2D.init(latitude:43.4592601, longitude: 10.36780120000003),rating: 0, description: "OTTIMA SINISTRA CHE ENTRA NELLA CALETTA DEI BAGNI ", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "NO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Quercianella", name: "Porto", position: CLLocationCoordinate2D.init(latitude:43.4592601, longitude: 10.36780120000003),rating: 0, description: "AFFIANCO AL PORTICCIOLO DI QUERCIANELLA TACK OFF VELOCE", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "NO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Quercianella", name: "Chioma", position: CLLocationCoordinate2D.init(latitude:43.4592601, longitude: 10.36780120000003),rating: 0, description: "AL PORTICCIOLO DI CHIOMA A SUD DEL PAESE RICHIEDE GRANDI MAREGGIATE", table: SpotInfoTable.init(wave: "DX", wind: "S-O (ATTIVO)", swell: "NO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Castiglioncello", name: "Bagni italia", position: CLLocationCoordinate2D.init(latitude:43.4047359, longitude: 10.418585500000063),rating: 0, description: "LATO NORD DELLA BAIA DEL BAGNO ITALIA RIPARATO DAL VENTO", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (ATTIVO)", swell: "SO-O", seabed: "MISTO")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Rosignano", name: "Garagolo", position: CLLocationCoordinate2D.init(latitude:43.387968, longitude: 10.438226600000007),rating: 0, description: "LATO NORD DEL PORTO DI ROSIGNANO IN CORRISPONDENZA DI UNA NAVE INCAGLIATA", table: SpotInfoTable.init(wave: "DX", wind: "S-O (MODERATO)", swell: "SO-O", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Rosignano", name: "Scoglietto, trieste", position: CLLocationCoordinate2D.init(latitude:43.387968, longitude: 10.438226600000007),rating: 0, description: "LUNGO IL LITORALE DI ROSIGNANO SOLVAY SEQUENZA DI REEF IDEALE IN SCADUTA DI LIBECCIO", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO-O-NO", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Rosignano", name: "Lillatro", position: CLLocationCoordinate2D.init(latitude:43.387968, longitude: 10.438226600000007),rating: 0, description: "TRE PICCHI SITUATI NEL GOLFO DI FRONTE ALLO STABILIMENTO DELLA SOLVAY. CON VENTO ATTIVO LAVORA SOLO IL PICCO Più A SINISTRA", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (ATTIVO)", swell: "SO-O-NO", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Piombino", name: "Perelli", position: CLLocationCoordinate2D.init(latitude:42.9256335, longitude: 10.525889099999972),rating: 0, description: "LUNGO LA SPIAGGIA LAVORA CON MAREGGIATE DI S,S/E O MARE ENORME DA O. NON BUONO CON MARE ATTIVO DA S/E, S/O", table: SpotInfoTable.init(wave: "DX-SX", wind: "S-O (MODERATO)", swell: "SO-O SE", seabed: "SABBIA")),
		             SpotInfo.init(region: "Toscana", province: "Li", city: "Ansedonia", name: "Ansedonia", position: CLLocationCoordinate2D.init(latitude:42.40812469999999, longitude: 11.28329629999996),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Liguria" : [SpotInfo.init(region: "Liguria", province: "Im", city: "Ventimiglia", name: "Le calandre", position: CLLocationCoordinate2D.init(latitude:43.7912366, longitude: 7.607586399999946),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Im", city: "Sanremo", name: "Tre ponti", position: CLLocationCoordinate2D.init(latitude:43.81596709999999, longitude: 7.7760567000000265),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Im", city: "Sanremo", name: "Bistrot", position: CLLocationCoordinate2D.init(latitude:43.81596709999999, longitude: 7.7760567000000265),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Im", city: "Diano", name: "Diano", position: CLLocationCoordinate2D.init(latitude:43.9088641, longitude: 8.082802399999991),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sv", city: "Andora", name: "Molo", position: CLLocationCoordinate2D.init(latitude:43.9848226, longitude: 8.130599200000006),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sv", city: "Alassio", name: "Alassio", position: CLLocationCoordinate2D.init(latitude:44.014336, longitude: 8.181174100000021),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sv", city: "Savona", name: "Il garden", position: CLLocationCoordinate2D.init(latitude:44.2975603, longitude: 8.464500000000044),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sv", city: "Varazze", name: "Pool", position: CLLocationCoordinate2D.init(latitude:44.3594336, longitude: 8.577312600000027),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sv", city: "Varazze", name: "Varazze reef", position: CLLocationCoordinate2D.init(latitude:44.3594336, longitude: 8.577312600000027),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sv", city: "Varazze", name: "Backdoor", position: CLLocationCoordinate2D.init(latitude:44.3594336, longitude: 8.577312600000027),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sv", city: "Arenzano", name: "Marina grande", position: CLLocationCoordinate2D.init(latitude:44.4058612, longitude: 8.686016699999982),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Ge", city: "Genova", name: "Capo marina", position: CLLocationCoordinate2D.init(latitude:44.4056499, longitude: 8.946255999999948),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Ge", city: "Recco", name: "Recco", position: CLLocationCoordinate2D.init(latitude:44.3614219, longitude: 9.143744500000025),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Ge", city: "Bogliasco", name: "Bogliasco", position: CLLocationCoordinate2D.init(latitude:44.3792927, longitude: 9.064765299999976),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Ge", city: "Chiavari", name: "Entella", position: CLLocationCoordinate2D.init(latitude:44.3168416, longitude: 9.319982200000027),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Ge", city: "Moneglia", name: "La secca", position: CLLocationCoordinate2D.init(latitude:44.239147, longitude: 9.488617699999963),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sp", city: "Levanto", name: "Levanto", position: CLLocationCoordinate2D.init(latitude:44.1686141, longitude: 9.610654000000068),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Liguria", province: "Sp", city: "Lerici", name: "Il castello - la venere", position: CLLocationCoordinate2D.init(latitude:44.0756332, longitude: 9.916933699999959),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Campania" : [SpotInfo.init(region: "Campania", province: "Na", city: "Procida", name: "Il lido", position: CLLocationCoordinate2D.init(latitude:40.7622633, longitude: 14.030954500000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Campania", province: "Sa", city: "Salerno", name: "Lungomare ovest", position: CLLocationCoordinate2D.init(latitude:40.68244079999999, longitude: 14.76809609999998),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Campania", province: "Sa", city: "Salerno", name: "Irno", position: CLLocationCoordinate2D.init(latitude:40.68244079999999, longitude: 14.76809609999998),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Campania", province: "Sa", city: "Salerno", name: "Yasmina beach", position: CLLocationCoordinate2D.init(latitude:40.68244079999999, longitude: 14.76809609999998),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Campania", province: "Sa", city: "Salerno", name: "Lido aurora", position: CLLocationCoordinate2D.init(latitude:40.68244079999999, longitude: 14.76809609999998),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Campania", province: "Sa", city: "Salerno", name: "Lido lago", position: CLLocationCoordinate2D.init(latitude:40.68244079999999, longitude: 14.76809609999998),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Campania", province: "Sa", city: "Salerno", name: "Lido la vela", position: CLLocationCoordinate2D.init(latitude:40.68244079999999, longitude: 14.76809609999998),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Campania", province: "Sa", city: "Acciaroli", name: "Acciaroli", position: CLLocationCoordinate2D.init(latitude:40.1762064, longitude: 15.03262989999996),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Lazio" : [SpotInfo.init(region: "Lazio", province: "Roma", city: "Civitavecchia", name: "L'ideale", position: CLLocationCoordinate2D.init(latitude:42.0924239, longitude: 11.795413199999984),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Civitavecchia", name: "Piccolo paradiso", position: CLLocationCoordinate2D.init(latitude:42.0924239, longitude: 11.795413199999984),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Civitavecchia", name: "Il marangone e 012", position: CLLocationCoordinate2D.init(latitude:42.0924239, longitude: 11.795413199999984),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Fregene", name: "Fregene", position: CLLocationCoordinate2D.init(latitude:41.8558992, longitude: 12.198098999999957),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Focene", name: "Focene", position: CLLocationCoordinate2D.init(latitude:41.817242, longitude: 12.211542099999974),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Ostia", name: "Lido di ostia", position: CLLocationCoordinate2D.init(latitude:41.7311182, longitude: 12.286269400000037),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Anzio", name: "Soldati", position: CLLocationCoordinate2D.init(latitude:41.4495955, longitude: 12.619725300000027),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Anzio", name: "Porto o marinetti", position: CLLocationCoordinate2D.init(latitude:41.4495955, longitude: 12.619725300000027),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Nettuno", name: "Belvedere", position: CLLocationCoordinate2D.init(latitude:41.4577305, longitude: 12.665491400000064),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Nettuno", name: "Chiesa", position: CLLocationCoordinate2D.init(latitude:41.4577305, longitude: 12.665491400000064),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Roma", city: "Nettuno", name: "Poligono", position: CLLocationCoordinate2D.init(latitude:41.4577305, longitude: 12.665491400000064),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Sabaudia", name: "Lilanda'", position: CLLocationCoordinate2D.init(latitude:41.3015823, longitude: 13.027575800000022),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Sperlonga", name: "Porto", position: CLLocationCoordinate2D.init(latitude:41.2636741, longitude: 13.427141399999982),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Sperlonga", name: "Mare", position: CLLocationCoordinate2D.init(latitude:41.2636741, longitude: 13.427141399999982),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Gaeta", name: "S. Agostino", position: CLLocationCoordinate2D.init(latitude:41.2107299, longitude: 13.571428500000025),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Gaeta", name: "San vito", position: CLLocationCoordinate2D.init(latitude:41.2107299, longitude: 13.571428500000025),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Gaeta", name: "Scissure", position: CLLocationCoordinate2D.init(latitude:41.2107299, longitude: 13.571428500000025),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Gaeta", name: "Ariana", position: CLLocationCoordinate2D.init(latitude:41.2107299, longitude: 13.571428500000025),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		           SpotInfo.init(region: "Lazio", province: "Latina", city: "Gaeta", name: "Separo", position: CLLocationCoordinate2D.init(latitude:41.2107299, longitude: 13.571428500000025),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Sardegna" : [SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Stintino", name: "Roachland", position: CLLocationCoordinate2D.init(latitude:40.9401332, longitude: 8.223588899999982),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "Porto ferro", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "Palo blanco", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "Le bombarde", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "Maddalenedda", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "Torre dei cani", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "Cannoni", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "El ventral", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "La speranza", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Sassari", city: "Alghero", name: "I piastroni", position: CLLocationCoordinate2D.init(latitude:40.5579517, longitude: 8.319294899999932),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Buggerru", name: "Portixxedu", position: CLLocationCoordinate2D.init(latitude:39.399722, longitude: 8.402429999999981),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Buggerru", name: "San nicolo'", position: CLLocationCoordinate2D.init(latitude:39.399722, longitude: 8.402429999999981),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Buggerru", name: "Il molo", position: CLLocationCoordinate2D.init(latitude:39.399722, longitude: 8.402429999999981),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Chia", name: "La torre", position: CLLocationCoordinate2D.init(latitude:38.90813190000001, longitude: 8.876944900000012),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Chia", name: "Flamingo", position: CLLocationCoordinate2D.init(latitude:38.90813190000001, longitude: 8.876944900000012),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Chia", name: "Cala cipolla", position: CLLocationCoordinate2D.init(latitude:38.90813190000001, longitude: 8.876944900000012),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Chia", name: "Pipeline", position: CLLocationCoordinate2D.init(latitude:38.90813190000001, longitude: 8.876944900000012),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Chia", name: "L'isolotto", position: CLLocationCoordinate2D.init(latitude:38.90813190000001, longitude: 8.876944900000012),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Chia", name: "Il morto", position: CLLocationCoordinate2D.init(latitude:38.90813190000001, longitude: 8.876944900000012),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Chia", name: "Il pontile", position: CLLocationCoordinate2D.init(latitude:38.90813190000001, longitude: 8.876944900000012),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Cagliari", name: "Poetto", position: CLLocationCoordinate2D.init(latitude:39.2136846, longitude: 9.171179499999994),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Capitana", name: "Il fortino", position: CLLocationCoordinate2D.init(latitude:39.2093022, longitude: 9.310803999999962),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Sardegna", province: "Cagliari", city: "Capitana", name: "Pocca point", position: CLLocationCoordinate2D.init(latitude:39.2093022, longitude: 9.310803999999962),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Calabria" : [SpotInfo.init(region: "Calabria", province: "Vibo valentia", city: "Zambrone", name: "La spiaggia", position: CLLocationCoordinate2D.init(latitude:38.7054031, longitude: 15.969562200000041),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		              SpotInfo.init(region: "Calabria", province: "Reggio calabria", city: "Siderno", name: "Renault", position: CLLocationCoordinate2D.init(latitude:38.2693662, longitude: 16.298308499999962),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Sicilia" : [SpotInfo.init(region: "Sicilia", province: "Catania", city: "Catania", name: "La playa", position: CLLocationCoordinate2D.init(latitude:37.5078772, longitude: 15.083030399999984),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Sicilia", province: "Palermo", city: "Cinisi", name: "Il reef", position: CLLocationCoordinate2D.init(latitude:38.155087, longitude: 13.108809699999938),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Sicilia", province: "Palermo", city: "Cinisi", name: "Magaggiari", position: CLLocationCoordinate2D.init(latitude:38.155087, longitude: 13.108809699999938),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Sicilia", province: "Palermo", city: "Trappeto", name: "Ciammarita", position: CLLocationCoordinate2D.init(latitude:38.068732, longitude: 13.042513900000017),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Sicilia", province: "Agrigento", city: "Sciacca", name: "San marco e ciminiera", position: CLLocationCoordinate2D.init(latitude:37.5085148, longitude: 13.08163049999996),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Puglia" : [SpotInfo.init(region: "Puglia", province: "Bari", city: "Brindisi", name: "Capo torre cavallo", position: CLLocationCoordinate2D.init(latitude:40.6327278, longitude: 17.941761600000063),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Bari", city: "Brindisi", name: "Vigili del fuoco", position: CLLocationCoordinate2D.init(latitude:40.6327278, longitude: 17.941761600000063),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Bari", city: "Brindisi", name: "Lido granchio rosso", position: CLLocationCoordinate2D.init(latitude:40.6327278, longitude: 17.941761600000063),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Bari", city: "Monopoli", name: "Capitolo", position: CLLocationCoordinate2D.init(latitude:40.9525166, longitude: 17.298555899999997),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Bari", city: "Bari", name: "Tombino", position: CLLocationCoordinate2D.init(latitude:41.1171432, longitude: 16.871871499999997),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Foggia", city: "Vieste", name: "La gattarella", position: CLLocationCoordinate2D.init(latitude:41.8824764, longitude: 16.176748900000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Foggia", city: "Vieste", name: "Pizzomunno", position: CLLocationCoordinate2D.init(latitude:41.8824764, longitude: 16.176748900000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Foggia", city: "Vieste", name: "Marina piccola", position: CLLocationCoordinate2D.init(latitude:41.8824764, longitude: 16.176748900000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Foggia", city: "Vieste", name: "Lo sperone", position: CLLocationCoordinate2D.init(latitude:41.8824764, longitude: 16.176748900000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Foggia", city: "Vieste", name: "La capuzza", position: CLLocationCoordinate2D.init(latitude:41.8824764, longitude: 16.176748900000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Foggia", city: "Vieste", name: "Punta lunga", position: CLLocationCoordinate2D.init(latitude:41.8824764, longitude: 16.176748900000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Puglia", province: "Foggia", city: "Vieste", name: "Baia molinella", position: CLLocationCoordinate2D.init(latitude:41.8824764, longitude: 16.176748900000007),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Molise" : [SpotInfo.init(region: "Molise", province: "Campobasso", city: "Campomarino", name: "Porto turistico", position: CLLocationCoordinate2D.init(latitude:41.9592663, longitude: 15.051268199999981),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Molise", province: "Campobasso", city: "Termoli", name: "Rio vivo", position: CLLocationCoordinate2D.init(latitude:42.0005331, longitude: 14.995283900000004),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Abruzzo" : [SpotInfo.init(region: "Abruzzo", province: "Chieti", city: "Vasto", name: "Porto", position: CLLocationCoordinate2D.init(latitude:42.0993726, longitude: 14.720308499999987),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Abruzzo", province: "Chieti", city: "Fossacesia marina", name: "Chiesetta", position: CLLocationCoordinate2D.init(latitude:42.0993726, longitude: 14.720308499999987),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		             SpotInfo.init(region: "Abruzzo", province: "Chieti", city: "Ortona", name: "Acquabella", position: CLLocationCoordinate2D.init(latitude:42.3522441, longitude: 14.40281129999994),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Marche" : [SpotInfo.init(region: "Marche", province: "Ascoli piceno", city: "Grottammare", name: "Tesino", position: CLLocationCoordinate2D.init(latitude:42.9853425, longitude: 13.8683671),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Sirolo", name: "Il sasso", position: CLLocationCoordinate2D.init(latitude:43.5191009, longitude: 13.621703400000001),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Portonovo", name: "La nave", position: CLLocationCoordinate2D.init(latitude:43.5611908, longitude: 13.599936999999954),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Portonovo", name: "Giacchetti", position: CLLocationCoordinate2D.init(latitude:43.5611908, longitude: 13.599936999999954),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Portonovo", name: "La torre", position: CLLocationCoordinate2D.init(latitude:43.5611908, longitude: 13.599936999999954),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Portonovo", name: "Il molo", position: CLLocationCoordinate2D.init(latitude:43.5611908, longitude: 13.599936999999954),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Portonovo", name: "Trocadero", position: CLLocationCoordinate2D.init(latitude:43.5611908, longitude: 13.599936999999954),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Senigallia", name: "Porto", position: CLLocationCoordinate2D.init(latitude:43.7197926, longitude: 13.215222400000016),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Ancona", city: "Senigallia", name: "Piramidi", position: CLLocationCoordinate2D.init(latitude:43.7197926, longitude: 13.215222400000016),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Pesaro urbino", city: "Fano", name: "Sassonia", position: CLLocationCoordinate2D.init(latitude:43.8398164, longitude: 13.019420099999934),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA")),
		            SpotInfo.init(region: "Marche", province: "Pesaro urbino", city: "Fano", name: "Lido", position: CLLocationCoordinate2D.init(latitude:43.8398164, longitude: 13.019420099999934),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))],
		
		"Veneto" : [SpotInfo.init(region: "Veneto", province: "Venezia", city: "Jesolo", name: "Iesolo", position: CLLocationCoordinate2D.init(latitude:45.5334198, longitude: 12.643849799999998),rating: 0, description: "SPIAGGIA A NORD DEL CENTRO ABITATO PICCHI SPARSI ANCHE NELLA SPIAGGIA A SUD DEL MONTE", table: SpotInfoTable.init(wave: "SX", wind: "S-O (MODERATO)", swell: "SE-S", seabed: "ROCCIA"))]
	]
	
	static func getSpotNameFromKey(key: String) -> [String]? {
		if let spotList = DICT[key] {
			var spotName = [String]()
			
			for spot in spotList{
				spotName.append(spot.nameSpot)
			}
			
			return spotName
			
		} else {
			return nil
		}
	}
	
	static func getSpotFromKey(key: String) -> [SpotInfo]? {
		if let spotList = DICT[key] {
			
			return spotList
			
		} else {
			
			return nil
		}
	}	
	
}
